CRITICAL - 2025-01-30 20:06:23 --> ErrorException: Undefined variable $query
[Method: GET, Route: users]
in APPPATH\Controllers\UserController.php on line 15.
 1 APPPATH\Controllers\UserController.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $query', 'C:\\xampp\\htdocs\\RepositorioCodeigniter\\app\\Controllers\\UserController.php', 15)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-01-30 20:33:29 --> Error: Call to a member function paginate() on null
[Method: GET, Route: users]
in APPPATH\Controllers\UserController.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-30 20:34:40 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseusuarios' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'baseusuarios', 3306, '', 0)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseusuarios' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#6 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-01-30 20:34:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseusuarios'
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE  LIKE :: ESCAPE \'!\'', [...], false)
 3 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-30 20:34:41 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseusuarios' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'baseusuarios', 3306, '', 0)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseusuarios' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#6 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-01-30 20:34:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseusuarios'
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE  LIKE :: ESCAPE \'!\'', [...], false)
 3 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-30 20:34:51 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'baseusuarios' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'baseusuarios', 3306, '', 0)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'baseusuarios' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#6 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-01-30 20:34:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'baseusuarios'
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 3 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-30 21:15:22 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'ci4' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'ci4' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#6 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-01-30 21:15:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'ci4'
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 3 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-30 21:15:23 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'ci4' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'ci4' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#6 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-01-30 21:15:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'ci4'
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 3 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-30 21:15:23 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'ci4' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'ci4' in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#6 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-01-30 21:15:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'ci4'
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 3 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-30 21:15:30 --> mysqli_sql_exception: Table 'infern_base.users' doesn't exist in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-01-30 21:15:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'infern_base.users' doesn't exist
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 2 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 3 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 4 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-01-30 21:15:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'infern_base.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 4 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 5 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 6 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-01-30 21:15:30 --> [Caused by] mysqli_sql_exception: Table 'infern_base.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 5 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 6 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 7 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-01-30 21:15:32 --> mysqli_sql_exception: Table 'infern_base.users' doesn't exist in C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\RepositorioCodeigniter\system\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\RepositorioCodeigniter\system\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\RepositorioCodeigniter\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\RepositorioCodeigniter\app\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
#7 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(933): App\Controllers\UserController->index()
#8 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#9 C:\xampp\htdocs\RepositorioCodeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\RepositorioCodeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\RepositorioCodeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-01-30 21:15:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'infern_base.users' doesn't exist
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 2 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 3 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 4 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-01-30 21:15:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'infern_base.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 4 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 5 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 6 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-01-30 21:15:32 --> [Caused by] mysqli_sql_exception: Table 'infern_base.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE \'%%\' ESCAPE \'!\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1728): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `name` LIKE :name: ESCAPE \'!\'', [...], false)
 5 SYSTEMPATH\Model.php(678): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 6 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 7 APPPATH\Controllers\UserController.php(17): CodeIgniter\BaseModel->paginate(3)
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserController->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2025-01-30 21:48:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-30 21:48:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-30 21:49:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-30 21:49:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-30 22:02:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-30 22:02:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-30 22:02:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-30 22:02:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
